# Generated by Django 4.2.3 on 2023-08-01 00:40

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OmbudsmanStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ost_title', models.CharField(max_length=100, verbose_name='Título')),
                ('ost_description', models.CharField(max_length=100, verbose_name='Descrição')),
                ('ost_create_user', models.CharField(default=django.contrib.auth.models.User.get_email_field_name, max_length=100, verbose_name='Descrição')),
                ('ost_create_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Data de Criação')),
            ],
        ),
        migrations.CreateModel(
            name='OmbudsmanPortalForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fm_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('fm_email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('fm_phone', models.CharField(max_length=100, verbose_name='Telefone')),
                ('fm_type_complaint', models.CharField(max_length=100, verbose_name='Tipo de Ocorrencia')),
                ('fm_complaint_description', models.CharField(max_length=100, verbose_name='Descrição da Ocorrencia')),
                ('fm_complaint_datetime', models.DateTimeField(verbose_name='Data da Ocorrencia')),
                ('fm_date_create', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Data de Criação')),
                ('fm_status_complaint', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Ombudsman_Portal.ombudsmanstatus')),
            ],
        ),
    ]
