# Generated by Django 4.2.3 on 2023-08-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ombudsman_Portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ombudsmanportalform',
            options={'ordering': ['fm_date_create'], 'verbose_name_plural': 'Tabela para Registro de Ocorrencias'},
        ),
        migrations.AlterModelOptions(
            name='ombudsmanstatus',
            options={'ordering': ['ost_title'], 'verbose_name_plural': 'Tabela de Registro de Status'},
        ),
        migrations.RemoveField(
            model_name='ombudsmanstatus',
            name='ost_create_user',
        ),
        migrations.AlterField(
            model_name='ombudsmanportalform',
            name='fm_complaint_description',
            field=models.CharField(max_length=99999, verbose_name='Descrição da Ocorrencia'),
        ),
        migrations.AlterField(
            model_name='ombudsmanportalform',
            name='fm_email',
            field=models.CharField(max_length=999, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='ombudsmanportalform',
            name='fm_name',
            field=models.CharField(max_length=999, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='ombudsmanportalform',
            name='fm_phone',
            field=models.CharField(max_length=999, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='ombudsmanportalform',
            name='fm_type_complaint',
            field=models.TextField(max_length=99999, verbose_name='Tipo de Ocorrencia'),
        ),
    ]
